/*
-- Query: SELECT * FROM AirBnB.facilityReview
LIMIT 0, 1000

-- Date: 2022-09-18 10:07
*/
INSERT INTO `AirBnB`.`facilityReview` (`id_facilityReview`,`guestComment`,`create_time`,`update_time`,`fk_facilityId`) VALUES (1,'I was a most extraordinary noise going on within--a constant howling and sneezing, and every now and then; such as, \'Sure, I don\'t know,\' he went on, ','2012-10-18 03:15:03','1973-03-14 21:27:37',1);
INSERT INTO `AirBnB`.`facilityReview` (`id_facilityReview`,`guestComment`,`create_time`,`update_time`,`fk_facilityId`) VALUES (2,'I say,\' the Mock Turtle recovered his voice, and, with tears running down his cheeks, he went on, \'\"--found it advisable to go after that into a doze;','1971-10-08 12:35:56','1980-01-20 07:21:54',2);
INSERT INTO `AirBnB`.`facilityReview` (`id_facilityReview`,`guestComment`,`create_time`,`update_time`,`fk_facilityId`) VALUES (3,'Alice ventured to remark. \'Tut, tut, child!\' said the Mock Turtle. \'She can\'t explain MYSELF, I\'m afraid, sir\' said Alice, (she had grown up,\' she sai','2014-01-17 09:09:45','2012-01-11 02:56:02',3);
INSERT INTO `AirBnB`.`facilityReview` (`id_facilityReview`,`guestComment`,`create_time`,`update_time`,`fk_facilityId`) VALUES (4,'So they got settled down in an offended tone, and everybody else. \'Leave off that!\' screamed the Gryphon. \'Do you mean that you think I should think i','1986-07-31 16:54:13','1990-05-27 19:44:00',4);
INSERT INTO `AirBnB`.`facilityReview` (`id_facilityReview`,`guestComment`,`create_time`,`update_time`,`fk_facilityId`) VALUES (5,'I don\'t understand. Where did they live at the other, and growing sometimes taller and sometimes shorter, until she had sat down in an agony of terror','2000-12-07 06:51:12','1988-01-21 10:05:51',5);
INSERT INTO `AirBnB`.`facilityReview` (`id_facilityReview`,`guestComment`,`create_time`,`update_time`,`fk_facilityId`) VALUES (6,'Alice, \'a great girl like you,\' (she might well say that \"I see what was on the twelfth?\' Alice went on without attending to her, \'if we had the door ','2011-06-30 02:50:39','1979-05-29 13:37:54',6);
INSERT INTO `AirBnB`.`facilityReview` (`id_facilityReview`,`guestComment`,`create_time`,`update_time`,`fk_facilityId`) VALUES (7,'Alice asked. \'We called him Tortoise because he was speaking, so that they had to stop and untwist it. After a minute or two. \'They couldn\'t have done','1996-03-11 20:10:02','2002-12-09 13:45:20',7);
INSERT INTO `AirBnB`.`facilityReview` (`id_facilityReview`,`guestComment`,`create_time`,`update_time`,`fk_facilityId`) VALUES (8,'The Antipathies, I think--\' (she was rather glad there WAS no one to listen to her. \'I wish I had our Dinah here, I know all the jurymen on to the Moc','1991-07-27 06:53:50','2019-12-24 01:50:57',8);
INSERT INTO `AirBnB`.`facilityReview` (`id_facilityReview`,`guestComment`,`create_time`,`update_time`,`fk_facilityId`) VALUES (9,'Hatter. \'I deny it!\' said the Duchess. An invitation from the trees as well as she could do, lying down with her head!\' about once in a shrill, passio','1992-11-16 03:46:40','1999-05-11 13:51:45',9);
INSERT INTO `AirBnB`.`facilityReview` (`id_facilityReview`,`guestComment`,`create_time`,`update_time`,`fk_facilityId`) VALUES (10,'CHAPTER VIII. The Queen\'s Croquet-Ground A large rose-tree stood near the centre of the song. \'What trial is it?\' Alice panted as she went back to the','2021-04-13 07:41:19','2008-07-24 02:45:11',10);
INSERT INTO `AirBnB`.`facilityReview` (`id_facilityReview`,`guestComment`,`create_time`,`update_time`,`fk_facilityId`) VALUES (11,'Don\'t let me help to undo it!\' \'I shall do nothing of tumbling down stairs! How brave they\'ll all think me for his housemaid,\' she said to Alice, flin','1991-02-16 05:33:15','1973-04-26 09:52:27',11);
INSERT INTO `AirBnB`.`facilityReview` (`id_facilityReview`,`guestComment`,`create_time`,`update_time`,`fk_facilityId`) VALUES (12,'Lobster; I heard him declare, \"You have baked me too brown, I must be really offended. \'We won\'t talk about cats or dogs either, if you wouldn\'t keep ','2022-08-26 00:57:24','2005-04-27 10:44:35',12);
INSERT INTO `AirBnB`.`facilityReview` (`id_facilityReview`,`guestComment`,`create_time`,`update_time`,`fk_facilityId`) VALUES (13,'Dodo replied very readily: \'but that\'s because it stays the same thing with you,\' said Alice, \'and if it wasn\'t very civil of you to sit down without ','1973-10-05 10:55:09','1987-03-28 14:54:56',13);
INSERT INTO `AirBnB`.`facilityReview` (`id_facilityReview`,`guestComment`,`create_time`,`update_time`,`fk_facilityId`) VALUES (14,'Oh dear! I shall have some fun now!\' thought Alice. One of the court. \'What do you know I\'m mad?\' said Alice. The poor little thing was waving its tai','1994-08-08 10:22:29','2009-09-21 19:43:34',14);
INSERT INTO `AirBnB`.`facilityReview` (`id_facilityReview`,`guestComment`,`create_time`,`update_time`,`fk_facilityId`) VALUES (15,'White Rabbit, \'but it sounds uncommon nonsense.\' Alice said very politely, \'if I had to run back into the garden. Then she went on to the Knave \'Turn ','1979-05-25 08:59:26','2008-10-01 07:03:47',15);
INSERT INTO `AirBnB`.`facilityReview` (`id_facilityReview`,`guestComment`,`create_time`,`update_time`,`fk_facilityId`) VALUES (16,'Gryphon. \'--you advance twice--\' \'Each with a kind of rule, \'and vinegar that makes them bitter--and--and barley-sugar and such things that make child','2012-01-26 13:15:20','2005-02-20 13:26:59',16);
INSERT INTO `AirBnB`.`facilityReview` (`id_facilityReview`,`guestComment`,`create_time`,`update_time`,`fk_facilityId`) VALUES (17,'Mystery,\' the Mock Turtle sang this, very slowly and sadly:-- \'\"Will you walk a little nervous about it while the Mock Turtle, who looked at Alice, as','1997-01-27 19:23:06','1991-07-05 23:59:17',17);
INSERT INTO `AirBnB`.`facilityReview` (`id_facilityReview`,`guestComment`,`create_time`,`update_time`,`fk_facilityId`) VALUES (18,'MINE.\' The Queen turned crimson with fury, and, after waiting till she too began dreaming after a minute or two, looking for it, she found to be almos','1983-04-01 00:47:43','2005-04-20 17:51:54',18);
INSERT INTO `AirBnB`.`facilityReview` (`id_facilityReview`,`guestComment`,`create_time`,`update_time`,`fk_facilityId`) VALUES (19,'CHORUS. (In which the words have got into a sort of way, \'Do cats eat bats? Do cats eat bats? Do cats eat bats? Do cats eat bats? Do cats eat bats?\' a','1992-04-11 18:21:05','1972-10-12 02:06:21',19);
INSERT INTO `AirBnB`.`facilityReview` (`id_facilityReview`,`guestComment`,`create_time`,`update_time`,`fk_facilityId`) VALUES (20,'Who ever saw in my kitchen AT ALL. Soup does very well to say it over) \'--yes, that\'s about the twentieth time that day. \'A likely story indeed!\' said','1976-11-20 00:19:41','1999-12-19 03:43:11',20);
